### ISSUE TITLE
请问用vllm推理llama-3-chinese-8b-instruct-v3，vllm和torch各自应该是什么版本？

### ISSUE THREAD

**Issue by lckj2009** [ymcui/Chinese-LLaMA-Alpaca-3#113]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

模型推理

### 基础模型

Llama-3-Chinese-8B-Instruct（指令模型）

### 操作系统

Linux

### 详细描述问题

python scripts/inference/inference_hf.py  --base_model /root/llama-3-chinese-8b-instruct-v3    --with_prompt   --interactive   --use_vllm 推理总是报错。

### 依赖情况（代码类问题务必提供）

目前出错的版本是：
torch==2.5.1
vllm-0.6.6.post1

### 运行日志或截图

INFO 12-30 10:49:42 selector.py:120] Using Flash Attention backend.
INFO 12-30 10:49:43 model_runner.py:1094] Starting to load model /root/llama-3-chinese-8b-instruct-v3...
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/bak/Chinese-LLaMA-Alpaca-3/scripts/inference/inference_hf.py", line 95, in <module>
[rank0]:     model = LLM(model=args.base_model,
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/utils.py", line 986, in inner
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 230, in __init__
[rank0]:     self.llm_engine = self.engine_class.from_engine_args(
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 517, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 273, in __init__
[rank0]:     self.model_executor = executor_class(vllm_config=vllm_config, )
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 36, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 35, in _init_executor
[rank0]:     self.driver_worker.load_model()
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/worker/worker.py", line 155, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1096, in load_model
[rank0]:     self.model = get_model(vllm_config=self.vllm_config)
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py", line 12, in get_model
[rank0]:     return loader.load_model(vllm_config=vllm_config)
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 366, in load_model
[rank0]:     loaded_weights = model.load_weights(
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 594, in load_weights
[rank0]:     return loader.load_weights(
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 237, in load_weights
[rank0]:     autoloaded_weights = set(self._load_module("", self.module, weights))
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 198, in _load_module
[rank0]:     yield from self._load_module(prefix,
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 207, in _load_module
[rank0]:     yield from self._load_param(prefix, child_params[child_prefix],
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/model_executor/models/utils.py", line 154, in _load_param
[rank0]:     weight_loader(param, weight_data)
[rank0]:   File "/root/anaconda3/envs/LLAMA/lib/python3.10/site-packages/vllm/model_executor/layers/vocab_parallel_embedding.py", line 382, in weight_loader
[rank0]:     assert loaded_weight.shape[output_dim] == self.org_vocab_size
[rank0]: AssertionError
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]

**Comment by liusssyang** [comment]
我也遇到这个问题了，你咋解决的？
