### ISSUE TITLE
训练过程种，异常中断问题

### ISSUE THREAD

**Issue by AnonymousDestroyer** [ymcui/Chinese-LLaMA-Alpaca-3#47]
### 提交前必须检查以下项目

- [X] 请确保使用的是仓库最新代码（git pull）
- [X] 已阅读[项目文档](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki)和[FAQ章节](https://github.com/ymcui/Chinese-LLaMA-Alpaca-3/wiki/常见问题)并且已在Issue中对问题进行了搜索，没有找到相似问题和解决方案。
- [X] 第三方插件问题：例如[llama.cpp](https://github.com/ggerganov/llama.cpp)、[text-generation-webui](https://github.com/oobabooga/text-generation-webui)等，建议优先去对应的项目中查找解决方案。

### 问题类型

None

### 基础模型

Llama-3-Chinese-8B-Instruct（指令模型）

### 操作系统

Linux

### 详细描述问题

```
# 请在此处粘贴运行代码（请粘贴在本代码块里）

 49%|████▉     | 2844/5772 [4:22:09<4:26:46,  5.47s/it]W0519 07:08:17.209025 139677327284032 torch/distributed/elastic/agent/server/api.py:741] Received Signals.SIGHUP death signal, shutting down workers
W0519 07:08:17.210792 139677327284032 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 589361 closing signal SIGHUP
W0519 07:08:17.210993 139677327284032 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 589435 closing signal SIGHUP
W0519 07:08:17.211277 139677327284032 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 589451 closing signal SIGHUP
W0519 07:08:17.211430 139677327284032 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 589452 closing signal SIGHUP
W0519 07:08:17.211654 139677327284032 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 589453 closing signal SIGHUP
W0519 07:08:17.211819 139677327284032 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 589454 closing signal SIGHUP
Traceback (most recent call last):
  File "/home/wangyujin/anaconda3/envs/llama/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 254, in launch_agent
    result = agent.run()
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 733, in run
    result = self._invoke_run(role)
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 876, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 76, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 585674 got signal: 1

```

### 依赖情况（代码类问题务必提供）

```
# 请在此处粘贴依赖情况（请粘贴在本代码块里）
```

### 运行日志或截图

```
 49%|████▉     | 2844/5772 [4:22:09<4:26:46,  5.47s/it]W0519 07:08:17.209025 139677327284032 torch/distributed/elastic/agent/server/api.py:741] Received Signals.SIGHUP death signal, shutting down workers
W0519 07:08:17.210792 139677327284032 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 589361 closing signal SIGHUP
W0519 07:08:17.210993 139677327284032 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 589435 closing signal SIGHUP
W0519 07:08:17.211277 139677327284032 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 589451 closing signal SIGHUP
W0519 07:08:17.211430 139677327284032 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 589452 closing signal SIGHUP
W0519 07:08:17.211654 139677327284032 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 589453 closing signal SIGHUP
W0519 07:08:17.211819 139677327284032 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 589454 closing signal SIGHUP
Traceback (most recent call last):
  File "/home/wangyujin/anaconda3/envs/llama/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 254, in launch_agent
    result = agent.run()
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 123, in wrapper
    result = f(*args, **kwargs)
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 733, in run
    result = self._invoke_run(role)
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 876, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/wangyujin/anaconda3/envs/llama/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 76, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 585674 got signal: 1
```

**Comment by AnonymousDestroyer** [comment]
好像已经找到问题，大家避开nohup去train

**Comment by AnonymousDestroyer** [comment]
ddp和nohup 貌似存在一些不兼容问题
